name: Go

on:
  release:
    types: [published, edited]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build archive
      run: make archive
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Upload archive
      uses: actions/upload-artifact@v1.0.0
      with:
        name: beiausp
        path: build
